package com.sebas.dialogsbasic.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF142700)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF314A12)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF1C2511)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF3C462F)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF002725)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF1A4A47)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF4E0002)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF8C0009)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFF9FAEF)
val onBackgroundLight = Color(0xFF1A1C16)
val surfaceLight = Color(0xFFF9FAEF)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFE1E4D5)
val onSurfaceVariantLight = Color(0xFF21251C)
val outlineLight = Color(0xFF404439)
val outlineVariantLight = Color(0xFF404439)


val primaryDark = Color(0xFFF4FFDF)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFB5D58E)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFF4FFDF)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFFC4CFB1)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFFEAFFFC)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFA4D4D0)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFF9F9)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFFFFBAB1)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF44483D)
val onSurfaceVariantDark = Color(0xFFF9FCED)
val outlineDark = Color(0xFFC9CCBE)
val outlineVariantDark = Color(0xFFC9CCBE)

